### ISSUE TITLE
conformance tests: group results by workflows

### ISSUE THREAD

**Issue by rchincha** [opencontainers/distribution-spec#108]
Pls. see https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/_GP6IqefKcg for some discussion

**Comment by rchincha** [comment]
https://github.com/opencontainers/distribution-spec/tree/master/conformance

Tests are already organized approximately based on workflows. Just tabulate them.
Fully conformant when *all* workflows are conformant.

**Comment by jdolitsky** [comment]
From the mailing list (@dmcgowan), this seems like a good breakdown in terms of priority:

```
1. Pull
2. Push - Registries need a way to get content to pull, but clients can be more forgiving here if needing to fallback after an unsupported endpoint
3. Content Discovery - Includes tag listing and possibly search in the future
4. Content Management - Includes tag, blob, repo deletion. Many registries may have other ways to accomplish this than the API.
```

@rchincha regarding "fully conformant", what I suggest is that workflow 1 be enough to be considered conformant. Workflows 2-4 will indicate additional conformance for predefined feature sets. Perhaps that means the spec doc needs updating to reflect it.

**Comment by jdolitsky** [comment]
For example, to trigger additional testing: 

```
export OCI_TEST_PUSH=1
export OCI_TEST_DISCOVERY=1
export OCI_TEST_MANAGEMENT=1
```

**Comment by rchincha** [comment]
> 
> 
> From the mailing list (@dmcgowan), this seems like a good breakdown in terms of priority:
> 
> ```
> 1. Pull
> 2. Push - Registries need a way to get content to pull, but clients can be more forgiving here if needing to fallback after an unsupported endpoint
> 3. Content Discovery - Includes tag listing and possibly search in the future
> 4. Content Management - Includes tag, blob, repo deletion. Many registries may have other ways to accomplish this than the API.
> ```
> 
> @rchincha regarding "fully conformant", what I suggest is that workflow 1 be enough to be considered conformant. Workflows 2-4 will indicate additional conformance for predefined feature sets. Perhaps that means the spec doc needs updating to reflect it.

What I had in mind was:
Full Conformance = (Pull_Conformance + Push_Conformance + ...)
Tools in any ecosystem which need only Pull_Conformance will continue to work.

If non-conformant, either the client or the registry or both are broken, so mark it so, and it may or may not matter, but important to spell it out.
