### ISSUE TITLE
Conformance test's config does not conform to spec

### ISSUE THREAD

**Issue by josephschorr** [opencontainers/distribution-spec#115]
According to the image spec, it appears the `rootfs` property is *required* in the config: https://github.com/opencontainers/image-spec/blob/master/config.md:

```rootfs object, REQUIRED```

However, it appears the conformance test suite is sending an empty configuration block:
https://github.com/opencontainers/distribution-spec/blob/4c5b810d62dfbe50310356019e598827a56312ed/conformance/setup.go#L92

Does the conformance suite need to be updated or is the intention for the `rootfs` property to be optional and assumed empty if not present?

**Comment by jdolitsky** [comment]
@josephschorr - there doesnt appear to be anything in this repo referencing "rootfs" or the format of the config. I was under the impression config doesn't even need to be JSON-formatted - it could be whatever format is understood by a given client

**Comment by josephschorr** [comment]
@jdolitsky See link above (https://github.com/opencontainers/image-spec/blob/master/config.md). Its required in the image spec for the Config, and I assume distribution maintains that if the mimetype of the config is used, it should match it semantically.

**Comment by jonjohnsonjr** [comment]
I don't think it violates anything in the distribution spec, but it does violate the expectations of the image spec. The registry is right (I think) to reject this image on the grounds that it's an invalid image, per the specification of the `application/vnd.oci.image.config.v1+json` media type.

You could fix that by either changing the media type to something else or changing the content to be a valid `application/vnd.oci.image.config.v1+json`.

**Comment by jdolitsky** [comment]
Makes sense. I'll modify that to look like minimal version of this example https://github.com/opencontainers/image-spec/blob/master/config.md#example
