### ISSUE TITLE
Enumerate the ways in which spec.md language/layout is unclear

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#117]
cc @pmengelbert

**Comment by jdolitsky** [comment]
related to https://github.com/opencontainers/distribution-spec/issues/62

**Comment by pmengelbert** [comment]
I began a list of issues with the spec here:
https://hackmd.io/ZlKd3uzMSgC98OAwOQ3SHQ?view

It's a working document but I hope to make it more complete. The 3 things that will likely make the biggest difference are:
* Combine overview and corresponding detail sections, and carefully remove all duplications.
* Mass `will be` to `MUST`
* Rewrite all language written from client perspective to be from registry perspective

**Comment by vbatts** [comment]
Related: #125

**Comment by vbatts** [comment]
i'm closing this issue, as there are other issues opened now, with discussion on this.
