### ISSUE TITLE
Question: version v1 vs. v2

### ISSUE THREAD

**Issue by vsoch** [opencontainers/distribution-spec#119]
heyo! I have a quick question about versions represented here. In the [spec.md](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#overview) it talks about a /v2/ endpoint, but then in the folder with code there is only [v1](https://github.com/opencontainers/distribution-spec/tree/master/specs-go/v1) represented. Are any of the following true?

 - the repository is serving version 1, which include a v2 endpoint as specified by the original Docker api (in other words, version 1 IS v2 for the specification).
 - the repository has version 1, and updated the spec for version 2, but has not yet written a v2 folder.
 - the code for v2 is the same as v1, so the v1 folder represents both versions.
 - something else?

Thanks for the clarification!

**Comment by dmcgowan** [comment]
Apparently we both had this topic on our mind at the same time #120 

OCI's 1.0 is based on Docker's 2.0 version. Since clients have mostly hardcoded `/v2`, it lives on in the API definitions. So the first one is true

**Comment by vsoch** [comment]
ah okay, this was my first instinct, but then I started to scratch my head and wonder if something else was the case. Thanks for the clarification, and speedy response! Since it's in the spec now, I'll honor it, and can update (to remove it) if needed. For registries serving versioned APIs it might (at some point) be useful to have an option to serve the various versions from different url bases. The alternative is to serve the same endpoints, but require some metadata from the client to specify the version needed. Anyway, thank you for the clarification.

**Comment by vsoch** [comment]
In case others stumble on this, what I'm trying for now (still under development) is clearly distinguishing these things in the application settings:

```python
DEFAULTS = {

    # Url base prefix
    'URL_PREFIX': "v2",

    # Version of distribution spec
    'SPEC_VERSION': "1",

    # Repository permissions
    'PRIVATE_ONLY': False,

    # Authentication
    ...
}
```
