### ISSUE TITLE
Separate /v2 from API endpoint definitions

### ISSUE THREAD

**Issue by dmcgowan** [opencontainers/distribution-spec#120]
The `/v2` was originally added to differentiate the v2 docker registry API from the v1 API. In the context of OCI, the v1 Docker API is completely deprecated and unused and the OCI distribution spec will be released as 1.0. While the `/v2` prefix is important for backwards compatible for clients, it is not a necessity in the API definition. I propose we strip the prefix from the definition and add a section explaining the role of the `/v2` prefix. Likewise, we should encourage clients to be explicit about how the `/v2` endpoint is affixed to form the API root, rather than just `<host> + /v2`. For example, when configuring a registry client, when a host is configured as OCI 1.0, it should have the corresponding prefix defined. Also when we add the discovery protocol in the future, the root of the API should be resolved to where `<host>/v2/` is today. Newer versions of the API after 1.0 could be at a completely different base URL.

Some previous discussions at #28

**Comment by mikebrow** [comment]
SGTM or at least reduce the number of times /v2 is prefixed throughout. Where there may be tables one could add a * reference to prefix section. If there is an actual example though, it may be confusing to not have the prefix there.

**Comment by vbatts** [comment]
I agree that Newer versions could use a different base, but I do not see a point in removing the `/v2` prefix at this point.
This reminds me of the image-spec, renaming "manifest-list" to "image-index", which I now regret.

**Comment by vbatts** [comment]
closing this issue. While containerd does a fine job of not even hitting this API endpoint, it has been an established endpoint, and no telling the scripts or such that do basic sniff testing of `/v2/` to get an `{}` body or http headers.
