### ISSUE TITLE
conformance: blob deletion tests do not take in to account deletes disabled

### ISSUE THREAD

**Issue by markphelps** [opencontainers/distribution-spec#121]
Blob deletion can return `405 Method Not Allowed`: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-method-not-allowed

This does not seem to be represented in the blob deletion conformance tests: https://github.com/opencontainers/distribution-spec/blob/master/conformance/09_blob_delete_test.go as they are looking for `202` and then `404` respectively

## Expected Results

1. First request returns a `405` because deletes are disabled: https://github.com/opencontainers/distribution-spec/blob/38956df5d3957ab35785c608f8cf715584f08a8d/conformance/09_blob_delete_test.go#L13
2. Second request allows for a `200` since the blob was never deleted: https://github.com/opencontainers/distribution-spec/blob/38956df5d3957ab35785c608f8cf715584f08a8d/conformance/09_blob_delete_test.go#L20

## Current Results

![Screen Shot 2020-03-30 at 11 41 48 AM](https://user-images.githubusercontent.com/209477/77932380-76544700-727b-11ea-8a5c-5377ea1f7f80.png)

**Comment by vbatts** [comment]
@pmengelbert @jdolitsky thoughts?

**Comment by pmengelbert** [comment]
@vbatts @markphelps This is addressed in our PR #123  which is currently open--registries will be able to disable tests that involve deletion.

**Comment by markphelps** [comment]
Sounds good to me! Feel free to close
