### ISSUE TITLE
conformance: error codes tests do not allow for deletion disabled

### ISSUE THREAD

**Issue by markphelps** [opencontainers/distribution-spec#124]
The test `Response from DELETE request to manifest URL (tag) should have OCI-conforming code`, expects a valid JSON response with errors

However if Deleting manifests is not supported by a registry, the request: `DELETE  /v2/myorg/myrepo/manifests/test0` may return a `405`, which makes the test fail:

![Screen Shot 2020-03-30 at 3 50 55 PM](https://user-images.githubusercontent.com/209477/77955533-56824a80-729e-11ea-8000-b2e66172ba1a.png)

**Comment by mikebrow** [comment]
should language is not the same as MUST language.. I read should as meaning may or may not based on whether or not DELETE is supported.

**Comment by markphelps** [comment]
@pmengelbert thank you for the explanation. I'm good with closing this since we know have the ability to disable the deletion tests via disabling the "Content Management" workflow tests.

I'll also make sure to update my code to return the appropriate error JSON body for `405 Method Not Allowed` as described here: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-not-allowed

**Comment by vbatts** [comment]
thanks @markphelps and @pmengelbert
