### ISSUE TITLE
conformance: remove skipped workflow categories from report

### ISSUE THREAD

**Issue by pmengelbert** [opencontainers/distribution-spec#128]
If a registry doesn't support a workflow, that workflow should be removed from the report to reduce clutter and increase the proportion of green results.

**Comment by mikebrow** [comment]
maybe a config option..

**Comment by pmengelbert** [comment]
See PR #130 -- In that pull request, `OCI_HIDE_SKIPPED_WORKFLOWS`, if set to `1` will hide any skipped flows from the report.

**Comment by pmengelbert** [comment]
Resolved by PR #130 -- closing the issue
