### ISSUE TITLE
spec: Consider removing references to UUID

### ISSUE THREAD

**Issue by amouat** [opencontainers/distribution-spec#13]
The spec constantly refers to UUID that reference a given upload e.g. the `Docker-Upload-UUID` header.

However, there's no real reason this needs to be a UUID, it's just a reference number or ID (as noted in the spec itself "While the uuid parameter may be an actual UUID, this proposal imposes no constraints on the format and clients should never impose any"). Could it be changed to just `id` or `refid` or some such?

**Comment by jzelinskie** [comment]
It just needs to be a unique value for the upload.

**Comment by atlaskerr** [comment]
+1
It could be changed to `OCI-Upload-ID`

**Comment by mikebrow** [comment]
@stevvooe is this true? or put another way what is the likelihood that popular legacy clients are going to throw an exception if the id does not fit some expected UUID form via regex validation?

**Comment by jonjohnsonjr** [comment]
FWIW GCR relies on that being true.

**Comment by vbatts** [comment]
@jonjohnsonjr are you saying GCR relies on the string of UUID _not_ being a strict uuid?

**Comment by jonjohnsonjr** [comment]
Yep, that's correct. We haven't had any issue with clients expecting an actual uuid (as far as I know), since clients just treat the "uuid" as an opaque string.

**Comment by mikebrow** [comment]
naming constraints :)

**Comment by vbatts** [comment]
PTAL @ #76
