### ISSUE TITLE
distribution-spec - how implemented in the wild?

### ISSUE THREAD

**Issue by vsoch** [opencontainers/distribution-spec#131]
hey maintainers! I'm working on a django-oci module to make it easy to deploy a (distribution-spec) conforming registry, and I'm thinking about the different ways to implement the storage. I want to do an implementation that is easy for a user to plug into their Django setup, and still is able to scale. My thinking is that if I provide plugins for the storages that are most widely used (e.g., S3 or Google Cloud Storage) then the user could just select the backend provider as a variable, and then provide credentials to the container and have the PUT / GET endpoints essentially return signed urls for the storage. I was thinking of starting with S3 because I learned this weekend it can be deployed "locally" with a Minio server (e.g., a did this for the Singularity client via [Singularity Registry Server](https://github.com/singularityhub/sregistry/pull/298) which has it's own library protocol that uses the multipart upload API for S3). My thinking is that the example implementation for django-oci could do something similar, and should default to supporting these more realistic implementations over some native django filesystem upload that is intended for gifs of cats but not container binaries. Before I jump into trying this implementation, I wanted to get your feedback on this, more specifically:

 - How are the implementations of the distribution spec done in the wild? 
 - Does it make sense to try for a default that can better scale, and more likely matches the storages that people are using (not standard Django upload to a File object)
 - Other than S3/Minio and Google Cloud Storage, are there other local storages that I should look into (maybe Ceph)?

Thanks a bunch for the feedback! I know it's weird times, and this is just a side project, so please take whatever time you need to respond.

**Comment by rchincha** [comment]
Hope this helps:
https://github.com/bloodorangeio/oci-distribution-conformance-results/blob/split-tests/README.md

**Comment by vbatts** [comment]
@vsoch did you close this thought out on your end?
With the conformance test suite, and the spec reorg, this hopefully is more clear.
I'll close this out for now, and if there are specific items still lingering, we can reopen issues.

**Comment by vsoch** [comment]
Yes, thank you @vbatts !
