### ISSUE TITLE
conformance: blobs should be deleted before manifests

### ISSUE THREAD

**Issue by pmengelbert** [opencontainers/distribution-spec#134]
In some cases, the tests are deleting manifests before blobs. Some registries auto-delete blobs when the manifest is deleted and no other manifests reference that blob. The order of the deletion should be reversed to prevent unintentional failures.

**Comment by mikebrow** [comment]
> In some cases, the tests are deleting manifests before blobs. Some registries auto-delete blobs when the manifest is deleted and no other manifests reference that blob. The order of the deletion should be reversed to prevent unintentional failures.

Unless we are adding a MUST limitation to the spec I'd rather test the delete of the manifest before the blob and check for success or failure.. if it returns no not allowed that should be an acceptable response, no? I think it's fair for the registry to work either way since the spec does not say MUST support auto-delete.. But I'd rather test and make sure we have one of the expected responses than tailor the tests to always pass by not testing the potential issues.

**Comment by jdolitsky** [comment]
@mikebrow - if a registry returns a "not allowed" it isn't considered having support for the content management workflow, and therefore these tests would not even be run in that scenario.

**Comment by mikebrow** [comment]
> @mikebrow - if a registry returns a "not allowed" it isn't considered having support for the content management workflow, and therefore these tests would not even be run in that scenario.

Where is that in the spec? That you can not return "not allowed" and be considered to have support for content management workflow? What other return code should be returned when the user attempts to do a delete of a manifest that is not allowed, by the registry, because the blobs are still there? or.. what do you mean by it isn't considered? Do you mean by this conformance test?  

I don't follow.

**Comment by jdolitsky** [comment]
@mikebrow alot of this is unanswered in the spec, which I'm hoping we can resolve soon with the rewrite.

What I mean is that not fully supporting the Content Management workflow is _ok_ (from a conformance perspective). But in the context of these tests, we shouldnt be so forgiving. If a registry provider runs the tests with `OCI_TEST_CONTENT_MANAGEMENT=1`, then no, I do not think 405 is an acceptable response. You're explicitly setting a flag that checks for a 200-level response on some of these endpoints.

The concept of 405 being ok is reflected in the fact that the tests can be run with`OCI_TEST_CONTENT_MANAGEMENT=0` and still pass despite several skipped tests.

Again, a lot of this is based on ongoing discussions, and should make its way into the markdown spec doc. The purpose of breaking the tests into 4 categories in the first place was to allow for a degree of conformance for a registry supporting the bare minimum, that bare minimum being the Pull workflow.

**Comment by mikebrow** [comment]
right and hard to do a pull without a push.. or some pre-loaded registry.

**Comment by jdolitsky** [comment]
@mikebrow I see what you're saying here. Either order is acceptable. 

Part of the challenge of putting these tests together is trying to find a one-size fits all approach to these endpoints. So I think changing the order is fairly benign so long as it doesn't cause additional failures across the registries we've already tested.

The story behind this - once we introduced the 4 categories, we actually triggered this error in zot registry. The originally submitted tests had the  "correct" order (blobs then manifests), and we accidentally switched it. cc @rchincha 

Considering the change in the inverse didn't cause any failures to go away across the registries, I'd almost consider this as a bug we introduced.

**Comment by jdolitsky** [comment]
It'd be considerable effort to support both orders, and I don't find it necessary to do so until we come across a registry that suffers the problem zot is having in the inverse.

**Comment by jdolitsky** [comment]
Looks like I was mistaken - the original test suite did manifest then blob: https://github.com/opencontainers/distribution-spec/blob/822d3a029084af27ea5ffdeaa2fc878ffaddee75/conformance/00_conformance_suite_test.go#L19

Most registries would garbage collect dangling blobs at some point, right? Maybe it's just that zot is doing it too quickly (immediately vs. middle of the night)

**Comment by jdolitsky** [comment]
@rchincha - is it possible to configure zot to disable auto-garbage collection? That may be the simplest solution here.

**Comment by rchincha** [comment]
> 
> 
> @rchincha - is it possible to configure zot to disable auto-garbage collection? That may be the simplest solution here.

@jdolitsky yes, this should be possible.

**Comment by rchamarthy** [comment]
@rchincha @jdolitsky its probably better to do a mark-sweep. We mark and add a timer and then we sweep if that blob is still garbage after the timer pop. Removing GC is probably asking for trouble. Infinite storage is a myth :)

**Comment by jdolitsky** [comment]
@rchamarthy all we need is about a 5 second window :)

**Comment by pmengelbert** [comment]
Closing this issue, since it seems to be more of a Zot issue than a conformance one.
