### ISSUE TITLE
Conformance: Discovery Test Should Push Test Blob

### ISSUE THREAD

**Issue by amouat** [opencontainers/distribution-spec#137]
For the discovery test to be standalone, it should first upload the "test blob", as is done in the pull test: https://github.com/opencontainers/distribution-spec/blob/master/conformance/01_pull_test.go#L19-L33

At the moment, Trow fails because the push tests run before the discovery tests, which include an explicit delete of the blob: https://github.com/opencontainers/distribution-spec/blob/master/conformance/02_push_test.go#L210-L219 . Trow checks the digest referenced in the manifest, can't find it and returns an invalid manifest error.

Alternatively the deletes could be removed.

**Comment by pmengelbert** [comment]
@amouat This takes place during the "setup" section of the discovery test -- in fact, this is the very first test. Is it possible that you have the setup disabled?

Do you have `OCI_TAG_LIST` set in the environment? Doing so will disable the setup for discovery.

**Comment by amouat** [comment]
@pmengelbert The discovery test uploads test tags, but it doesn't upload the *blob* referenced in the manifest. 

For most registries this doesn't matter, as the blob is uploaded in the pull test - it later gets deleted in the push test, but most registries don't support blob deletes so this line is effectively ignored.

If you can, try running the discovery test without first running the pull test on an empty registry - all of them should fail assume they properly check manifests.

**Comment by pmengelbert** [comment]
@amouat My mistake -- I was looking at unmerged changes! PR #133 actually uploads the blob in question

**Comment by amouat** [comment]
Ah, excellent! Thanks :)

**Comment by jzelinskie** [comment]
Can we close this now that #133 is merged?

**Comment by pmengelbert** [comment]
@jzelinskie @jdolitsky Yes, this can be closed now.

**Comment by amouat** [comment]
Not sure if it was bad practice to close this myself. I'm never sure of GitHub ettiquette... :)
