### ISSUE TITLE
spec: To add version identifiers, or not to?

### ISSUE THREAD

**Issue by xiaods** [opencontainers/distribution-spec#14]
API versioning is common case in api design. i suggest give a practical way to design the distribution api group.

REF: https://apigee.com/about/blog/developer/common-misconceptions-about-api-versioning

**Comment by mikebrow** [comment]
```
All endpoints will be prefixed by the API version and the repository name:

/v2/<name>/
```
This is to distinguish from legacy v1.

**Comment by xiaods** [comment]
thanks.
