### ISSUE TITLE
Conformance test manifest has wrong number of history entries

### ISSUE THREAD

**Issue by josephschorr** [opencontainers/distribution-spec#147]
The conformance test manifest references a single layer/blob in the layers list:

https://github.com/opencontainers/distribution-spec/blob/5882031c0bace290aa88710bdc1aaf21146808ac/conformance/setup.go#L191

However, the *config* for the manifest references zero history entries:

https://github.com/opencontainers/distribution-spec/blob/5882031c0bace290aa88710bdc1aaf21146808ac/conformance/setup.go#L167

This would seem to indicate an invalid configuration for this manifest, and Quay's validation code is currently failing on it. Are we being too strict, or is this an oversight in the compliance suite?

**Comment by jdolitsky** [comment]
@josephschorr this is probably an oversight, just as the original config was an empty json (`{}`). Do you have any other validation on the manifest before we attempt a fix?

**Comment by jdolitsky** [comment]
*manifest config

**Comment by jzelinskie** [comment]
[the history field is optional in the imagespec](https://github.com/opencontainers/image-spec/blob/master/config.md), but quay uses it to generate backwards compatibility for docker v1. I think this isn't technically an issue for conformance

**Comment by josephschorr** [comment]
@jdolitsky Nope; this is the only change we saw.

We're going to investigate making the history entry optional on our side as well.
