### ISSUE TITLE
Referencing artifacts

### ISSUE THREAD

**Issue by mattfarina** [opencontainers/distribution-spec#148]
As I see the distribution spec nearing a release I'm trying to figure out how it relates to [artifacts](github.com/opencontainers/artifacts/). If artifacts other than images are ok to put into a distribution can it be noted or referenced in the distribution spec or the notes surrounding it?

I'm trying to determine what is stable and mainline vs what is an experiment.

**Comment by jdolitsky** [comment]
Started on a [reorganization of the spec](https://github.com/opencontainers/distribution-spec/pull/146/files#diff-958e7270f96f5407d7d980f500805b1bR4661), and as part of that using the term "artifact" instead of "image" to make things feel more general-purpose. 

See glossary here, with no reference to "image": 

- **Registry**: a HTTP service which implements this spec
- **Client**: a tool that communicates with registries over HTTP
- **Push**: the act of uploading content to a registry
- **Pull**: the act of downloading content from a registry
- **Artifact**: a single piece of content, made up of a manifest and one or more layers
- **Manifest**: a JSON document which defines an artifact
- **Layer**: a single part of all the parts which comprise an artifact
- **Config**: a special layer defined at the top of a manifest containing artifact metadata
- **Blob**: a single binary content stored in a registry
- **Digest**: a unique blob identifier
- **Content**: a general term for content that can be downloaded from a registry (manifest or blob)

I'm not sure I fully understand how artifacts fits in and the relationship between the two repos. For the case of Helm charts, it is used as guidance as far as which fields on the manifest to modify for a custom type (i.e. `manifest.config.mediaType`). Other than that, as far as I understand, pushing a Helm chart is fully compliant with the distribution spec. It may violate IANA regulations regarding the media type used (`application/vnd.cncf.helm.config.v1+json`), but that's a separate story, and should be responsibility of the Helm team to submit this.

Paging @SteveLasker - is artifacts considered more of a "best practices" guide vs. a specification in and of itself?

**Comment by mikebrow** [comment]
Artifacts: 
```
This `[Artifacts]` repository provides a reference for artifact authors and registry implementors for supporting new artifact types with the existing implementations of distribution. More particularly this repository has been tasked by the OCI TOB to serve 3 primary goals:

artifact authors - guidance for authoring new artifact types. Including a clearing house for well known artifact types.
registry operators and vendors - guidance for how operators and vendors can support new artifact types, including how they can opt-in or out of well known artifact types. Registry operators that already implement media-type filtering will not have to change. The artifact repo will provide context on how new media-types can be used, and how media-types can be associated with a type of artifact.
clearing house for well known artifacts - artifact authors can submit their artifact definitions, providing registry operators a list by which they can easily support.
```
no spec

**Comment by jzelinskie** [comment]
This repository does not attempt to reference artifacts at all; it is concerned with container images only. Rather, we leave some leniency in this specification such that container registries can optionally support anything defined in the artifact specification, but need not be required to do so.

The artifacts repository effectively describes how to use the leniency present in the distribution-spec to optionally support arbitrary content and also documents well known content so that implementations can validate popular content.

**Comment by SteveLasker** [comment]
There are a few things here:
- We did agree the distribution-spec is now generalized to store any type of artifact. Images being a specific type of artifact. We created [issue # 9 in artifacts](https://github.com/opencontainers/artifacts/issues/9) to track this. We have been focusing on getting the artifacts content merged, completed last week. There's additional artifact repo content coming for registry operators that will talk about how artifacts are to be supported. The artifact spec doesn't say all registry operators must support all artifact types. 
- Versioning: We've gone back and forth on this. As @mikebrow and @dmcgowan point out, when we initially approved artifacts, we said non-versioned. We debated this during the artifacts content authoring, and reverted the `spec.md` for [artifact-authors.md](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md) as part of [this pr comment](https://github.com/opencontainers/artifacts/pull/13#pullrequestreview-401195432).

@mattfarina brings up a valid question of clarity on what is actually approved. 

I do think having the distribution spec reference artifacts is more clear, with oci-image being one of many artifact types supported.

**Comment by mattfarina** [comment]
@jzelinskie what does _some leniency_ mean? Are artifacts an experiment? Are they more?

Here is my problem... how does a project, like Helm, decide artifacts are stable enough for the majority? In this case I'll use the same criteria the CNCF uses. There they use crossing the chasm where they talk about experiments, early adoptions, majority, etc.

One one side, artifacts could be an experiment or a hack on top of image registries. On the other side, it's a thought out intentional part of them. Then there are points in between.

Can the OCI broadcast in some documented manner where artifacts are at?

**Comment by vbatts** [comment]
It may be worth having an agreed upon maturity of particular mediaTypes/mime-types in the artifacts repo.
The thing about the Artifacts effort is to help the community clearly dereference how to handle new/different mediaTypes that may be fetched/stored. The _behaviour_ is already in the distribution-spec.

**Comment by SteveLasker** [comment]
The process for publishing well-known types will be in the next PR. That said, it doesn't stop an artifact author from authoring their type. In this case both Helm and Singularity are the most mature. We're working with the Singularity folks on next steps. While I agree we should add more clarity, I'm struggling on what the blocker is for Helm to move forward. 
They can move forward with the IANA registration. There's nothing blocking their use of their current mediaType. Registering their type just avoids a future conflict. Up until recently, we didn't even have the OCI types registered. We only have one validation type completed thus far.

**Comment by jzelinskie** [comment]
It looks like a lot of braindumps going on here, but not answering many questions for @mattfarina.

>@jzelinskie what does some leniency mean? Are artifacts an experiment? Are they more?

Leniency is mostly about making sure the _container_ specification does not require any behavior that would preclude artifacts support. This repository is for the specification of the _container_ standard and that is its scope. This repository does not describe the ability to store arbitrary artifacts using the same protocol.

>how does a project, like Helm, decide artifacts are stable enough for the majority?

Arbitrary artifacts is entirely optional behavior that container registries can choose to support, but not all will choose to do so. In addition, not all registries will support all possible artifact types, which is the significance of having some kind of "clearing house" or a way to reserve mediatypes for well known artifacts. This will always be a hurtle for consumers, such as Helm, regardless of the stability or blessing from OCI.

The OCI distribution specification for containers isn't even 1.0.0. We're currently focused on closing the final issues and making sure our conformance tests give us the proper understanding of each registry's implementation before we finalize.

I consider artifacts to be something more than an experiment, because the community has been experimenting for many years now and we know that we need this behavior to be formalized. But, we are in still in the process for formalizing that process and so behavior is likely to change that could break implementations.

**Comment by mikebrow** [comment]
related issue: https://github.com/opencontainers/artifacts/issues/23

**Comment by SteveLasker** [comment]
> Leniency is mostly about making sure the container specification does not require any behavior that would preclude artifacts support. This repository is for the specification of the container standard and that is its scope. This repository does not describe the ability to store arbitrary artifacts using the same protocol.

There's likely a bit of minor confusion as @mattfarina opened two issues across artifacts and the distribution-spec. @mikebrow was correlating the two above.  However, the word leniency is what Matt is pointing out as not very actionable with confidence. 
The scope has evolved and the [scope table was removed as an example](https://github.com/opencontainers/tob/pull/74/files). The distribution-spec does indirectly say it can store arbitrary artifacts using the same protocol. The artifacts repo simply formalizes that process to use the existing distribution-spec apis. The update Josh is working on to update the distribution-spec, using Artifacts to generalize content, where image is one type of artifact would add that clarity. Is there a reason to not do this? 

> Arbitrary artifacts is entirely optional behavior that container registries can choose to support, but not all will choose to do so.

This is true. As registry operators, vendors and projects are customer driven, we expect operators, vendors and projects will support these as customers have artifacts to store. This circle dependency is what we're trying to break. If we can give confidence we won't break them, we can break the circle dependency.

> In addition, not all registries will support all possible artifact types, which is the significance of having some kind of "clearing house" or a way to reserve mediatypes for well known artifacts. This will always be a hurtle for consumers, such as Helm, regardless of the stability or blessing from OCI.

We did initially think PRs on the artifacts repo would be the clearing house. Through the review process, it was pointed out that IANA is the right way to claim ownership of a mediaType. This process [Registering Unique Types with IANA](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md#registering-unique-types-with-iana) has been added to the artifacts repo. 
We will have an updated version of [Publishing the Artifact Type](https://github.com/opencontainers/artifacts/blob/f9710ad60b6de311843df88d8f8fa1e6d0d44b50/authoring-artifacts.md#optional-publishing-the-artifact-type) to submit [well-known types](https://github.com/opencontainers/artifacts/blob/master/definitions-terms.md#well-known-type), but that will be more of a meta-data model for displaying information in registries. Artifacts is no longer a "clearing house" from an approval, rather an optional way for well known types to publish their info. 

> ...But, we are in still in the process for formalizing that process and so behavior is likely to change that could break implementations.

@jzelinskie  What do you see that could change? The merger of the artifacts pr is the intent to NOT break anyone. This is precisely the point @mattfarina is making. I agree we should add versioning, for clarity [Releases Please #23](https://github.com/opencontainers/artifacts/issues/23#issuecomment-627463748), but as an artifacts maintainer and tob member, it's our commitment to not break folks.

**Comment by mattfarina** [comment]
Let me try to use an example here... the distribution spec refers to images. I don't see it talking about storing other things.

I know people have tried to load other things into registries in the past. It's a total hack to put those things in there but some folks do that. If the spec is just for images than how is something else going in not another hack?

If this spec referred to other artifacts besides images that would alleviate this issue. Even if it didn't name them.

**Comment by mikebrow** [comment]
Not to derail, but more context in the conversation would help in the understanding why it's seen as a hack, what else is desired / needed for it not to be viewed as a hack.

The image is defined, in part, as a Layer Filesystem Changeset.  Some people look at a container image and see application, or platform, or service, ... But there's no rule that an image can't merely be an artifact definition that other images use as a layer to build an application, or platform, or service.

**Comment by mattfarina** [comment]
@mikebrow Sorry, I can add more context. [Helm](https://helm.sh/) has an experimental feature to store charts (i.e. packages for the package manager) in OCI registries using artifacts (as implemented by [oras](https://github.com/deislabs/oras/). We want to see the experimental flag be removed.

But, the distribution spec says it's for [images](https://github.com/opencontainers/image-spec/). It specifically says,

> This specification defines an API protocol to facilitate distribution of images.

Helm charts are [artifacts](https://github.com/opencontainers/artifacts/) that are not images.

If the specification said it was for images and other artifacts I would see the link between artifacts and distribution. At the moment there is nothing linking artifacts and distribution. I am left concluding that distribution is for images which leaves other artifacts out. This is what lead to my comment that sticking other things in distributions would be a hack. It's doing something that's out of spec.

**Comment by mikebrow** [comment]
@mattfarina fair enough and thx, that sets the context stage for the issue you are talking about.  We need a process for new non-oci image layer/blob mime types. If the new types function in the same manner as blob/layers of an image then we can say images and artifacts that function as blobs/layer in the distribution spec, or something similar in the distribution spec and artifact guidance. If we need a config for the new artifact types, a new artifact manifest type etc., then we'll need more and that may or may not be in scope for the first distribution spec and first set of artifact guidance docs. @SteveLasker can summarize better or and in more detail but I think we are heading in the right direction to close your issue.

Cheers, Mike

**Comment by SteveLasker** [comment]
As @mikebrow points out, the distribtuion-spec supports additional types today. As discussed in this issue, Artifacts provides guidance for how you create and manage `manifest.config.mediaTypes` to avoid having to "hack" other content into the same `vnd.oci.image` mediaTypes.
As well-known types are discussed further, we'll likely have more details that are unique to artifacts that would need a versioning to adhere to a schema. We're not yet at that point.
We're also working on some distribution spec refactoring that will update the terminology. But, again, this doesn't change the definition of the spec. It's about updating the format. Which will likely include wording around images and artifacts. \

**Comment by mattfarina** [comment]
@SteveLasker I wonder if we are caught up on language. I think that language matters in this case. Here's why...

The distribution spec says images. When you consider images there are assumptions you can make around what you can do with them. [Singularity is a good example of this and it's called out in the artifacts repo](https://github.com/opencontainers/artifacts/). It's another image type packaged up in a different manner.

But, when artifacts are not images you can't make the same assumptions. Helm charts are not images and do not resemble images. If the distribution spec is for images it makes sense to extend the types to other types of images. But, if the distribution spec is for images than non-image things could be seen as a bit of a hack.

Distribution spec reads, today, as if it's for images and you can extend it with new well-known image types. I want to use it for non-images.

Language matters and if the spec authors want to keep it focused on images that's ok. It does make me question putting non-images into something implementing the distribution-spec. If the spec authors are ok with non-images, what holds that back from being documented in the spec?

**Comment by SteveLasker** [comment]
@mattfarina , can you represent this on the OCI weekly call: https://hackmd.io/El8Dd2xrTlCaCG59ns5cwg#May-20

**Comment by mikebrow** [comment]
definitely language semantics.. if a helm chart can be stored in a scratch container.. what else is that container but a helm chart..

**Comment by mattfarina** [comment]
@mikebrow I think this highlights an interesting problem in the language and expectations. Something on a scratch container has a mime type for a container image. A Helm chart has a completely different mime type. You can make assumptions about container images, such as they are filesystems that can be mounted and scanned. For a Helm chart that doesn't apply. Helm charts in repo require no containers or parent of scratch.

**Comment by mattfarina** [comment]
@SteveLasker I'll try to come to an upcoming meeting. I have had conflicts or I would have come already.

**Comment by mikebrow** [comment]
> @mikebrow I think this highlights an interesting problem in the language and expectations. Something on a scratch container has a mime type for a container image. A Helm chart has a completely different mime type. You can make assumptions about container images, such as they are filesystems that can be mounted and scanned. For a Helm chart that doesn't apply. Helm charts in repo require no containers or parent of scratch.

yes.. support for brand new mime types at the registry and client portions of the stack seems to be the sticking point. 

From scratch means you are starting from nothing, so me saying building a helm chart from scratch, is I believe, the technical equivalent to you saying the helm chart requires no containers or parent from scratch in the repo. 

I haven't looked at the code yet, but after skimming https://helm.sh/docs/topics/registries/ I feel like we may be in violent agreement.

**Comment by jdolitsky** [comment]
@mattfarina please see the new introduction section this spec: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#introduction

Does this suffice?

**Comment by SteveLasker** [comment]
I've proposed this: https://github.com/opencontainers/distribution-spec/issues/202

**Comment by vbatts** [comment]
with the reorg merge, I think this issue is fully addressed
