### ISSUE TITLE
Option to disable blob deletion in teardown (or teardown itself) of push test suite

### ISSUE THREAD

**Issue by josephschorr** [opencontainers/distribution-spec#150]
The teardown for the compliance push test suite makes use of the `DELETE` API for blobs (see: https://github.com/opencontainers/distribution-spec/blob/master/conformance/02_push_test.go#L249). As discussed in some previous meetings, many registries do not implement this endpoint, which makes them fail the compliance suite even though they pass the overall test itself. 

Would it be possible to add an env var to disable the use of this API or one that simply skips the teardown entirely, to be used for tests where the registry is reset between each call?

**Comment by jzelinskie** [comment]
I think that this endpoint shouldn't be skipped in the conformance tests, but also be changed to also accept 415 as a passing status code.

**Comment by pmengelbert** [comment]
@josephschorr You raise a good point -- "content management" (deletion) is its own separate workflow, so registries shouldn't be seeing red when teardown fails for push. I believe we put that in the teardown simply for convenience. I agree with @jzelinskie that allowing a Method Not Allowed response there is ideal.

@jzelinskie you mean 405, not 415 right?
