### ISSUE TITLE
Conformance: Why do we test 'DELETE request to manifest tag should return 202' ?

### ISSUE THREAD

**Issue by Wwwsylvia** [opencontainers/distribution-spec#157]
![image](https://user-images.githubusercontent.com/8113721/84022398-c278e180-a9b8-11ea-899f-4ff309fe4975.png)

Does the test expect a manifest to be deleted by specifying a tag? If so, it seems differ from the [distribution-spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#delete-manifest), which says "A manifest can only be deleted by digest."

![image](https://user-images.githubusercontent.com/8113721/84111833-43d48080-aa5a-11ea-80a9-2639d6c80ab2.png)

And I'm wondering why the error code has to be "UNSUPPORTED" for 400... Is something like "DIGEST_INVALID" acceptable?

**Comment by jdolitsky** [comment]
@Wwwsylvia there was a discussion about this endpoint. PLease see https://github.com/opencontainers/distribution-spec/issues/102#issuecomment-594733958

**Comment by jdolitsky** [comment]
But it still needs to be reflected properly in the spec

**Comment by Wwwsylvia** [comment]
Thanks @jdolitsky
