### ISSUE TITLE
Conformance: Allow 405 Status for all tear down / deletes

### ISSUE THREAD

**Issue by markphelps** [opencontainers/distribution-spec#179]
Much like what was implemented in https://github.com/opencontainers/distribution-spec/pull/151/files#diff-fddb7a1636af89303c8fcf32651486a9R260 for `02_push_test.go`, it would be great if you could allow this for all the other tests.

For example, our registry does not currently support deletion through the CLI, so all of the other tests are failing in the tear down step with errors such as:

```
 OCI Distribution Conformance Tests
/go/src/github.com/opencontainers/distribution-spec/conformance/00_conformance_suite_test.go:12
  Pull
  /go/src/github.com/opencontainers/distribution-spec/conformance/01_pull_test.go:14
    Teardown
    /go/src/github.com/opencontainers/distribution-spec/conformance/01_pull_test.go:154
      Delete manifest created in setup [It]
      /go/src/github.com/opencontainers/distribution-spec/conformance/01_pull_test.go:191

      Expected
          <int>: 405
      to be <
          <int>: 300

      /go/src/github.com/opencontainers/distribution-spec/conformance/01_pull_test.go:197
```

It seems like `HTTP 405` s should be allowed in the teardown of the following tests:

1. `01_pull_test.go`
2. `03_discovery_test.go`
3. `04_management_test.go`

Thanks!

**Comment by markphelps** [comment]
@jdolitsky friendly bump

**Comment by jdolitsky** [comment]
@markphelps I think that this is reasonable. To clarify - you're talking specifically about the conformance tests and not changing error codes listed here https://github.com/opencontainers/distribution-spec/blob/master/spec.md#endpoints ?

**Comment by markphelps** [comment]
@jdolitsky yup correct. just talking about changing the conformance tests to allow for `HTTP 405` status responses for all tear down calls to delete

**Comment by markphelps** [comment]
I can happily create a PR as well if you like
