### ISSUE TITLE
Regular expressions missing for name, reference, etc.

### ISSUE THREAD

**Issue by vsoch** [opencontainers/distribution-spec#183]
Heyo! Is there a regular expression for the `<name>` attribute?

> <name> refers to the namespace of the repository. <reference> MUST be either (a) the digest of the manifest or (b) a tag name. The <reference> MUST NOT be in any other format.

I was using `[a-z0-9]+(?:[._-][a-z0-9]+)*` but I was under the impression that the name should allow a slash (e.g., `owner/repository`). Thanks!

------------------

Update: we would want the regular expressions for any fields mentioned for the distribution spec to be included here, in a code-agnostic format (e.g., the link below compiles it in golang).

**Comment by sajayantony** [comment]
Does this help - https://github.com/docker/distribution/blob/2800ab02245e2eafc10e338939511dd1aeb5e135/reference/regexp.go#L53

**Comment by vsoch** [comment]
yes perfect, thank you!

**Comment by vsoch** [comment]
Just curious, why isn't this knowledge ported over to this repository?

**Comment by sajayantony** [comment]
@mikebrow @jdolitsky - I don’t know if this repo has the constraints called out. @vsoch It does makes sense to have it in the spec repo.

**Comment by vsoch** [comment]
There is detail about regular expressions for the range in [spec.md](https://github.com/opencontainers/distribution-spec/blob/master/spec.md) but the name (and others) were missing. I can re-open the issue and rescope to have regular expressions represented here! I think this is important because someone should be able to read the spec and implement the distribution spec without needing to reference other repos.

**Comment by jdolitsky** [comment]
Hey yall, I've just added it to the spec revamp epic: https://github.com/opencontainers/distribution-spec/issues/126

**Comment by vsoch** [comment]
Thank you!

**Comment by jdolitsky** [comment]
Resolved by #206
