### ISSUE TITLE
Spec seems to be missing cross-repo mounting entirely

### ISSUE THREAD

**Issue by jonjohnsonjr** [opencontainers/distribution-spec#186]
This section from the docker spec seems to have been dropped: https://github.com/docker/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/api.md#cross-repository-blob-mount

I see that some info is still present in detail.md, which isn't referenced by spec.md at all: https://github.com/opencontainers/distribution-spec/blob/master/detail.md

Was this omission intentional?

**Comment by jdolitsky** [comment]
I think the omission is intentional, as mounting isn't fully worked out for 1.0 release. Was discussed that this, along with extensions, and other topics can be reworked/re-added for subsequent releases.

It is intended that detail.md will be referenced in spec.md prior to 1.0

**Comment by jonjohnsonjr** [comment]
> Was discussed that this, along with extensions, and other topics can be reworked/re-added for subsequent releases.

Interesting! Do you remember where the discussion took place? Have a link handy?

**Comment by jdolitsky** [comment]
@jonjohnsonjr It was a vidchat several weeks ago between maintainers related to getting this PR merged: https://github.com/opencontainers/distribution-spec/pull/178

Since we didn't want to lose useful bits, big chunk was saved off into details.md, although it shouldn't be considered "official". Working on adding that language in #188 

@vbatts - correct me if I'm wrong about punting extensions stuff until after 1.0

**Comment by dmcgowan** [comment]
> I think the omission is intentional, as mounting isn't fully worked out for 1.0 release.

I don't think that is accurate. Mounting is fully defined and regularly used today, I haven't heard of any aspect of it that was considered to be in-progress.

**Comment by jdolitsky** [comment]
@dmcgowan ok, lets add it back. Which section should it be defined under?

**Comment by dmcgowan** [comment]
Next to regular blob push. Used when initiating a new upload

**Comment by jdolitsky** [comment]
@jonjohnsonjr @dmcgowan please see https://github.com/opencontainers/distribution-spec/pull/204

**Comment by jdolitsky** [comment]
Resolved by #206
