### ISSUE TITLE
spec intro a little tighter

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/distribution-spec#202]
> The Open Container Initiative Distribution Specification (a.k.a. "OCI Distribution Spec") defines an API protocol to facilitate and standardize the distribution of content.
> While this specification is designed to be agnostic to content types, much of it is centered around the distribution of container images. Many of the concepts here, such as "manifests" and "digests", are originally defined in the Open Container Initiative Image Format Specification (a.k.a. "OCI Image Spec"), and the OCI Image is considered to be the primary supported artifact type.
> For guidance on how to apply this specification to other artifact types, please see the Open Container Initiative Artifact Authors Guide (a.k.a. "OCI Artifacts").

The spec is certainly originally focused on containers. As we've seen, there are already more uses cases, prior to OCI Artifacts. We've also seen the distribution spec is pretty vague about what it actually stores as none of the `mediaTypes`, nor even the sequence of events for pushing content (layers, config, manifest) are defined. 

The intro is a little more generic, but can I suggest the following:

---

_First paragraph remains the same:_
> The Open Container Initiative Distribution Specification (a.k.a. "OCI Distribution Spec") defines an API protocol to facilitate and standardize the distribution of content.

While OCI Image is the most prominent, the specification is designed to be agnostic of content types. Concepts such as "manifests" and "digests", are currently defined in the [Open Container Initiative Image Format Specification](https://github.com/opencontainers/image-spec) (a.k.a. "OCI Image Spec").

To support other artifact types, please see the [Open Container Initiative Artifact Authors Guide](https://github.com/opencontainers/artifacts) (a.k.a. "OCI Artifacts").

**Comment by jdolitsky** [comment]
Resolved by #206
