### ISSUE TITLE
V2 Client library clarification

### ISSUE THREAD

**Issue by dmcgowan** [opencontainers/distribution-spec#23]
Currently there is language about the inclusion of `V2 Client library implementation`. This is somewhat confusing as a client library is not part of the scope, however such a library may be useful for conformance testing.  We should update this language to mention conformance testing as a primary goal and within scope, and any library used for testing as a non-goal but potentially something we can support out of that work. Additionally there are many client libraries implementations in existence today, we may want to use one for the testing or create a new one, either way no opinion on a preferred library should be specified.

**Comment by mikebrow** [comment]
On PR #21 I committed a change to the line in question to now say: "- V2 Client (Consumer) requirements" to better express what is contained in the distribution-spec (proper)

agree with the comments.

**Comment by vbatts** [comment]
The conformance testing effort will likely provide some basics of this, even if just data structures.
Also, currently there is a _minimal_ amount of these structures in `./specs-go/`.
I for one am encouraging of the most minimal set of logic that can be imported by others for their own conformance validations, but not for feature rich development to happen on this spec repo.
Closing this for now as I think it's progressing
