### ISSUE TITLE
Feature: Multiple architecture support

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#242]
From original spec:

> Multiple architecture support

**Comment by sargun** [comment]
Doesn't this get handled in the image spec with the "fat manifest" format?

**Comment by jdolitsky** [comment]
I think that is the same thing yea. Perhaps this was written prior to that being introduced?

**Comment by sargun** [comment]
Oh, I mean, my comment was more so that this sounds like something that lives in the image spec over the distribution-spec.

**Comment by AkihiroSuda** [comment]
This issue can be closed?

**Comment by sudo-bmitch** [comment]
Closing this out as handled by image-spec with the Index manifest. If something was missed, we can reopen.
