### ISSUE TITLE
Fixing of tables in release PDF?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#258]
See the last few pages of https://github.com/opencontainers/distribution-spec/releases/download/v1.0.0-rc2/oci-distribution-spec.pdf

**Comment by mikebrow** [comment]
looks a little better in html.. same problems with md tables in the conversion to pdf in the other spec releases...

**Comment by jdolitsky** [comment]
Is there any way to fix this? Or should we let it go? cc @vbatts

**Comment by mikebrow** [comment]
Just a wild guess looking at the output it feels like the default margins are not good for our tables.. maybe go wide paper and/or narrow margin?  Found these options: " -V geometry:paperwidth=8in -V geometry:paperheight=12in -V geometry:margin=.5in "

**Comment by jdolitsky** [comment]
@mikebrow thanks, currently looking into it :) part is just needing a newer pandoc version

**Comment by jdolitsky** [comment]
plz see #263
