### ISSUE TITLE
Audit active maintainers

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/distribution-spec#262]
Vincent Batts	Thu Apr 1 19:54:30 2021 -0400
Josh Dolitsky	Thu Apr 1 17:11:09 2021 -0400
Jon Johnson	Wed Mar 31 11:51:18 2021 -0700
Derek McGowan	Wed Mar 24 13:17:33 2021 -0700
Shay Bagants	Sun Dec 20 21:43:27 2020 +0200
Mike Brown	Tue Dec 15 15:16:50 2020 -0600
Vanessasaurus	Tue Dec 15 14:16:26 2020 -0700
Peter Engelbert	Tue Dec 15 15:15:45 2020 -0600
jdolitsky	Wed Dec 9 16:58:26 2020 -0500
Sebastiaan van Stijn	Tue Nov 3 16:16:43 2020 +0100
nnnayan	Wed Oct 7 08:20:44 2020 -0700
Mark Phelps	Wed Oct 7 11:20:06 2020 -0400
Stefan Majewsky	Thu Jun 11 13:36:31 2020 +0200
Wang Yan	Fri May 22 02:53:30 2020 +0800
wang yan	Fri Apr 24 22:51:31 2020 +0800
Jimmy Zelinskie	Mon Mar 2 16:28:01 2020 -0500
Serge Hallyn	Thu Feb 27 13:24:31 2020 -0600
Adrian Mouat	Wed Feb 12 16:33:35 2020 +0000
Ramkumar Chinchani	Mon Jan 6 13:21:47 2020 -0800
Steve Lasker	Thu Oct 10 14:57:21 2019 -0700
Fabian Freyer	Mon Apr 22 09:14:03 2019 +0200
Atlas Kerr	Wed Feb 13 13:48:37 2019 -0600
Vanessa Sochat	Tue Feb 26 12:07:10 2019 -0500
Dongsu Park	Wed Dec 19 16:06:25 2018 +0100
Chris Aniszczyk	Wed Jan 16 13:21:22 2019 -0600
Luca Bruno	Mon Jan 14 10:06:46 2019 +0000
Stephen Day	Wed Jul 18 13:08:01 2018 -0700
W. Trevor King	Mon Apr 9 21:47:29 2018 -0700
Stephen J Day	Fri Apr 6 13:30:15 2018 -0700
Per Lundberg	Fri Dec 29 14:40:15 2017 +0200
Misty Stanley-Jones	Fri Oct 20 11:16:21 2017 -0700
LingFaKe	Thu Sep 22 12:01:13 2016 +0800
Qiao Anran	Mon Oct 17 13:40:33 2016 +0800
Aaron Lehmann	Tue Jul 12 12:18:54 2016 -0600
Richard Scothern	Wed Jun 8 10:39:17 2016 -0700
allencloud	Thu Jun 2 13:31:13 2016 +0800
Stefan Weil	Tue Feb 23 22:33:38 2016 +0100
Brian Bland	Wed Jan 13 11:44:42 2016 -0800
Sven Dowideit	Thu Dec 3 21:11:10 2015 +1000
Patrick Devine	Wed Dec 2 17:26:52 2015 -0800
Morgan Bauer	Mon Nov 23 12:59:51 2015 -0800
Josh Hawn	Mon Sep 28 10:41:18 2015 -0700
Olivier Gambier	Wed Aug 26 11:08:13 2015 -0700
Alex Chan	Fri Jul 31 13:36:43 2015 +0100
Richard	Wed May 27 10:52:22 2015 -0700
Jianqing Wang	Fri Jul 24 11:40:26 2015 +0800
Vincent Demeester	Fri Jun 26 10:34:48 2015 +0200
Mary Anthony	Tue Jun 16 06:00:24 2015 -0700
Doug Davis	Wed Jun 3 06:52:39 2015 -0700
Vincent Giersch	Mon Jun 1 15:14:03 2015 +0000
Nathan Sullivan	Sat Apr 4 01:03:43 2015 +1000
Nghia Tran	Thu Mar 19 13:13:53 2015 -0700
xiekeyang	Sat Feb 28 11:38:38 2015 +0800

**Comment by mikebrow** [comment]
For audit purposes I'd like to report that all maintainers in this repository have remained active, for example voting for the most recent release candidates commits via email and/or PR reviews.

**Comment by vbatts** [comment]
true enough. It seemed the most of the conversation was around image-spec, really.

**Comment by vbatts** [comment]
the distribution-spec maintainers seem active enough. Thanks for the audit.
closing for now.
