### ISSUE TITLE
Call for distribution-spec existing maintainers to step down if no longer active

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/distribution-spec#266]
Call for @opencontainers/distribution-spec-maintainers existing maintainers to step down if no longer active

We will leave this open for a couple of weeks

**Comment by vbatts** [comment]
for these maintainers, as you choose to step down, your vote is still useful on #265 for us to stably bring on new maintainers

**Comment by stevvooe** [comment]
I was hoping to represent a position on the maintainers as a user of container technology, rather than a vendor. I've been active in various discussions but have been unable to commit.
