### ISSUE TITLE
The specification needs some formalization

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/distribution-spec#27]
certain language like "must" should be converted to "MUST" when describing an absolute requirement of the specification.

**Comment by atlaskerr** [comment]
I'm gonna tackle this one this week, hopefully by Thursday.

**Comment by jzelinskie** [comment]
Fixed in #46.

**Comment by mikebrow** [comment]
Additional formalization is required above just upper casing the prior must type verbage.

**Comment by mikebrow** [comment]
Short list skimming over the first 250 lines.

Example 1 (line 192): ```All client implementations SHOULD treat unknown error codes as UNKNOWN, allowing future error codes to be added without breaking API compatibility. For the purposes of the specification error codes will only be added and never removed.```

Should->MUST

Example 2 (line 206): ```The client SHOULD be prepared to ignore this data.```

Informal, and incomplete.. should be rewritten.

208-209 needs to be reconciled with the earlier statements about authentication.. 

211 ```If `404 Not Found` response status, or other unexpected status, is returned, the client SHOULD proceed with the assumption that the registry does not implement V2 of the API.```

1) or other unexpected status? is there a list ..  2) remove should and assumption.. use MUST language.

213-215 ```When a `200 OK` or `401 Unauthorized` response is returned, the "Docker-Distribution-API-Version" header SHOULD be set to "registry/2.0". Clients MAY require this header value to determine if the endpoint serves this API. When this header is omitted, clients MAY fallback to an older API version.```

1) not clear why we would talk about older api versions .. 2) needs to be resolved with the docker/oci table when done. 3) SHOULD and MAY language should be revised here  think.

246 ```compliant implementations SHOULD use sha256```

SHOULD -> MUST at least support sha256.. ???

**Comment by mikebrow** [comment]
need to address: `<!--- TODO: add relevant background information here --->`

**Comment by mikebrow** [comment]
skimming over the error section.. there's a lot of MAY and SHOULD language that seems to render the processing of said error "indefinite"  

Consider rewriting to make these more definite, with MUST language and explain more specifically what is OPTIONAL.

**Comment by atlaskerr** [comment]
@mikebrow  Ugh it seems like I'm gonna have to use my brain on this one. I'll open a PR today and ping you  later this week when a roughdraft is ready.

**Comment by mikebrow** [comment]
There's a lot of "will be" language throughout to be revised.  The Issue I think is that the spec was written from a what the client should expect. Versus what the Registry and Client MUST implement.

**Comment by mikebrow** [comment]
Anyhow that is my summary of the glaring issues I see when skimming. You may find others when reading through.

**Comment by mikebrow** [comment]
Feel free to tackle one section or problem at a time it's a fairly lengthy spec.

**Comment by atlaskerr** [comment]
Do you think that is would be a blocker for the RC? I think it's kinda important we get the language right so there is time to review.

**Comment by dmcgowan** [comment]
We will have time to discuss this in the meeting later. I am going through and finding a few places where we can tighten up the language. The most important thing for RC though is freezing the API for 1.0, we can still fix the language.

**Comment by mikebrow** [comment]
that makes sense.. thus formalization isn't as important as replacing catalog :)

**Comment by atlaskerr** [comment]
Can we bump this to the V1 milestone?

**Comment by pmengelbert** [comment]
> There's a lot of "will be" language throughout to be revised. The Issue I think is that the spec was written from a what the client should expect perspective, versus a what the Registry and Client MUST implement perspective.

@mikebrow @atlaskerr We agree-- and actually this is in some cases preventing progress on the conformance test suite.  We don't know if the "will be"s are actually MUSTs (and thus are critically important to test) or SHOULDs (less critical) or even MAYs (not in need of a test at all)

**Comment by mikebrow** [comment]
> > There's a lot of "will be" language throughout to be revised. The Issue I think is that the spec was written from a what the client should expect perspective, versus a what the Registry and Client MUST implement perspective.
> 
> @mikebrow @atlaskerr We agree-- and actually this is in some cases preventing progress on the conformance test suite. We don't know if the "will be"s are actually MUSTs (and thus are critically important to test) or SHOULDs (less critical) or even MAYs (not in need of a test at all)

Yes we need a PR to s/will be/MUST/ after a quick skim they look like they should have been MUST.

**Comment by vbatts** [comment]
@mikebrow can you either close this out, or maybe make the original message a checklist to work through?
It's a little messy to scroll through the comments to find the action items.

**Comment by mikebrow** [comment]
@vbatts will reopen later when I have some time to make a list of MUST language fixes. I've seen some confusion around should language thinking that means MUST and some will be language that needs to be MUST. I'm sure others will chime in. But I agree we can start this one over focusing on specifics.
