### ISSUE TITLE
Distribution spec cross blob mount test does not upload original blob

### ISSUE THREAD

**Issue by vsoch** [opencontainers/distribution-spec#276]
I'm looking at the test here:

https://github.com/opencontainers/distribution-spec/blob/7108d95fe5fd0360d2a5084d8ceb7f37b95fbc60/conformance/02_push_test.go#L206

And I'm not seeing anywhere in the suite that this other repository blob is actually uploaded. E.g., so my registry will not find the blob and default to the next case of returning and upload session. Am I missing something?

**Comment by jonjohnsonjr** [comment]
I believe that happens here: https://github.com/opencontainers/distribution-spec/blob/7108d95fe5fd0360d2a5084d8ceb7f37b95fbc60/conformance/02_push_test.go#L42

**Comment by vsoch** [comment]
Oh I see - I misread the new docs for mount and had switched the repos in the return so it was just returning the wrong name. This mount thing is new to me - sorry for the noise!
