### ISSUE TITLE
definition needed for repository..

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/distribution-spec#279]
Repository was not defined in the spec.

Notes:

Repository in a sense refers to storage namespace for a group or organization in a container registry.

docker pull request:
```
pull [registry_host_name|IP address][:port][/v2][/org_path]<image_name>[:tag|@DIGEST]`
```
`/org_path` is (refers to) the repository at the registry host

Various registries have implemented repositories in different ways .. and some are tied to authentication/login

For example, does the registry allow sub domains in the /org_path, different answers from different registries here.
As another example who owns the root domain is root supported...

**Comment by sudo-bmitch** [comment]
Fixed by #325.
