### ISSUE TITLE
_catalog reserved reference missing from the current spec

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/distribution-spec#306]
PR #69 moved the `_catalog` api to reserved, to assure current implementations didn't get clobbered with a new implementation of the same API.
This reference was lost in 1.0 version of the spec. 

Opening an issue to get agreement on where we'd like to account for reserved elements of the spec.

**Comment by vbatts** [comment]
uuuhmm. I'm missing something. Your PR removed it, but now this is a discussion to re-add it as reserved?

**Comment by SteveLasker** [comment]
PR #69 had [text around it being reserved](https://github.com/opencontainers/distribution-spec/pull/69/files#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545R709)

> The `_catalog` api is reserved for historical usage. Registries MAY implement _catalog, but are NOT required.

I was looking for this reference to describe what some registries have implemented as an option for repo listing. I'd like to introduce a new pattern but wanted to refer to `_catalog` as not being supported. 
I'm hopeful we can use #111 as a way to get a scoped list of repos.

If folks agree with restoring the reserved `_catalog` reference, I can make the pr to bring it back as reserved.

**Comment by vbatts** [comment]
the existence and implementation of `_catalog` was a wart, and I don't think reserving it fixes or changes anything. 
The proper fix would be to provide proper way for search/listing to be possible.

**Comment by SteveLasker** [comment]
I completely agree we should implement a new listing and search API, that acknowledges the org and repo permission boundaries registries have implemented. See #71 for the most recent discussion, which also references #111 as the base.
But, the `_catalog` wart was part of the spec, and several registries implemented it. The line that got lost was simply capturing `_catalog` is reserved so it's not clobbered with new implementations.

**Comment by sajayantony** [comment]
I think we can close this now as it is marked reserved here -  https://github.com/opencontainers/distribution-spec/commit/12ffe009f98353c65b8c5f10d771b4999b0a3d16
