### ISSUE TITLE
The next release(s)

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#315]
What will be/should be included in

- `v1.0.2` ?
- `v1.1.0` ([existing milestone](https://github.com/opencontainers/distribution-spec/milestone/6))?

as raised in dev call today
cc @sudo-bmitch @vbatts

The [Extensions API](https://github.com/opencontainers/distribution-spec/tree/main/extensions#extensions-api-for-distribution)  discovery endpoint (IMO) is a feature that people are starting to use for experimentation, and are already talking about dist-spec 1.1 even though it doesn't exist yet.

**Comment by sudo-bmitch** [comment]
Automatic content discovery is another one of those nice features to highlight in the next release, and to make sure we include conformance tests.

**Comment by sudo-bmitch** [comment]
Sparse index support being the 3rd feature that jumps out to me. Both this and automatic content discovery may need switches on any conformance test to indicate if the registry is declaring they should support it.

**Comment by vbatts** [comment]
@sudo-bmitch links to those issues?

**Comment by sudo-bmitch** [comment]
Closing this out since we had the 1.1.0 release. 🎉
