### ISSUE TITLE
Conformance test for chunked upload needs more than one chunk

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/distribution-spec#317]
The [conformance test for chunked uploads](https://github.com/opencontainers/distribution-spec/blob/cf3ca0c741716a2c04c54de46c7a31af82596edb/conformance/02_push_test.go#L21-L51) only sends a single patch and put request. We should test multiple patch requests to test multiple chunks being uploaded to a registry and verify the digest calculation across multiple requests works on the registry.

**Comment by jdolitsky** [comment]
this is not new for 1.1, we just never tested it
