### ISSUE TITLE
TAG_INVALID in conformance tests is not present is spec

### ISSUE THREAD

**Issue by flavianmissi** [opencontainers/distribution-spec#319]
The `TAG_INVALID` error code is currently being checked by the [conformance tests](https://github.com/opencontainers/distribution-spec/blob/05097b7fad1ba0e433ed956cdb444e06874be6aa/conformance/setup.go#L302), but it's not mentioned in [the specification](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes).

Should `TAG_INVALID` be added to the spec, or should it be removed from the comformance tests?

**Comment by sudo-bmitch** [comment]
This was removed from the distribution-spec back in #206. Is this throwing an error for you? It may be useful for UX when interacting with registries that implement the [docker registry spec](https://docs.docker.com/registry/spec/api/#errors-2).

**Comment by flavianmissi** [comment]
No errors no. I thought I'd bring it up because although they are accepted error codes in the conformance tests, they are not listed in the list of acceptable error codes so I was a bit confused.
i.e
> The code field MUST be one of the following:
Except the code can also be TAG_INVALID or MANIFEST_UNVERIFIED.

Am I nitpicking?
