### ISSUE TITLE
Vote for release of 1.1.0-rc1 of distribution-spec

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#349]
We need 6 approvals from the current 8 maintainers on mailing list as per - https://github.com/opencontainers/distribution-spec/blob/main/GOVERNANCE.md#voting to vote for tagging 1dfa4f4 as `v1.1.0-rc1`

- [x] Brandon Mitchell (@sudo-bmitch)
- [x] Derek McGowan (@dmcgowan)
- [x] Jimmy Zelinskie (@jzelinskie)
- [ ] Jon Johnson (@jonjohnsonjr)
- [x] Josh Dolitsky (@jdolitsky)
- [x] Mike Brown (@mikebrow)
- [x] Stephen Day (@stevvooe)
- [x] Vincent Batts (@vbatts)

The next step in the process after the email votes would be to merge the PR https://github.com/opencontainers/distribution-spec/pull/348 and tag the commit voted upon so that the release may proceed.

Calling @opencontainers/distribution-spec-maintainers.

This issue was created as per discussion on the OCI call and help from multiple members on that call.

**Comment by sudo-bmitch** [comment]
https://groups.google.com/a/opencontainers.org/g/dev/c/PMgIqSNi14g
