### ISSUE TITLE
OCI_NAMESPACE in test `Cross-Repository Blob Mount` tests

### ISSUE THREAD

**Issue by ChristianKniep** [opencontainers/distribution-spec#405]
The `Cross-Repository Blob Mount` tests are not using the specified `OCI_NAMESPACE` within the configuration of the test suite.

I specified `oci/conformance`, but the request are issued against: 
```
~~~ REQUEST ~~~
POST  /v2/conformance-a3368016-1fc8-4b00-b904-eba7460e2599/blobs/uploads/?mount=sha256%3Ab94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9  HTTP/1.1
HOST   : localhost:8080
HEADERS:
	User-Agent: distribution-spec-conformance-tests
BODY   :
***** NO CONTENT *****
```

As I am only allowlist the namespace `oci/conformance` this test fails already in the auth step.

**Comment by ChristianKniep** [comment]
They are constructed slightly different from the rest of the pack. 🤔 
https://github.com/opencontainers/distribution-spec/blob/c3e48b9d94b104d5e3db2f984bb83a55fb7ac023/conformance/02_push_test.go#L285

**Comment by jdolitsky** [comment]
If you need a custom namespace for crossmount tests, you can use `OCI_CROSSMOUNT_NAMESPACE`

```
export OCI_CROSSMOUNT_NAMESPACE="myorg/other"
```
