### ISSUE TITLE
deprecate "legacy" headers?

### ISSUE THREAD

**Issue by rchincha** [opencontainers/distribution-spec#409]
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#legacy-docker-support-http-headers

Docker-Content-Digest, or Docker-Distribution-API-Version
^ should these become OCI-Content-Digest and OCI-Distribution-API-Version?

**Comment by sudo-bmitch** [comment]
https://github.com/opencontainers/distribution-spec/issues/26
