### ISSUE TITLE
Conformance: push/pull by digest test is needed

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/distribution-spec#412]
I've encountered at least one registry that doesn't allow pulling a manifest until it has been pushed with a tag (so after pushing by digest, a pull is responding with a 404). I don't think that follows the spec, but we would want a conformance test to verify registries support pushing and pulling by digest.

**Comment by emaa991** [comment]
Fdsggsyxzgvcfh

**Comment by jdolitsky** [comment]
wondering if this is resolved by any open PRs?
