### ISSUE TITLE
question regarding index with `subject` but without `artifactType`

### ISSUE THREAD

**Issue by qweeah** [opencontainers/distribution-spec#458]
OCI image spec 1.1.0-rc4 allows image index to have `subject`(updated in [this commit](https://github.com/opencontainers/image-spec/commit/c6854a626fb485c5a889cfe3ac9f3cd7e09dae60)) and `artifactType`(update in [this commit](https://github.com/opencontainers/image-spec/commit/749ea9a27d1eb44b5369ee7e8e296c7e99e3d2e5)). Since both fields are optional, it's possible that user can push an index with `subject` but no `artifactType` like below.

```mermaid
flowchart
index --subject--> image
```

My questions is: should such index be considered as valid when being pushed? If yes,
1) When Referrers API is enabled and user is trying to get the referrers of `image`, should the descriptor of `index` be included in the returned value of Referrers API? 
2) When Referrers API is not enabled, client need to add a descriptor to the referrers index, what should the `artifactType` be in the newly added descriptor? [Distribution-spec 1.1.0 rc3 ](https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc3/spec.md#pushing-manifests-with-subject:~:text=The%20value%20of%20the%20artifactType%20MUST%20be%20set%20to%20the%20artifactType%20value%20in%20the%20image%20manifest%2C%20if%20present.%20If%20the%20artifactType%20is%20empty%20or%20missing%20in%20the%20image%20manifest%2C%20the%20value%20of%20artifactType%20MUST%20be%20set%20to%20the%20config%20descriptor%20mediaType%20value.) only covers image referrer but not mentioning index.

**Comment by jdolitsky** [comment]
resolved in #500
