### ISSUE TITLE
Image name should allow uppercase letters

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [opencontainers/distribution-spec#466]
Currently the spec mandates the name to be lower-cased, but there is no reason why. Rather than strictly following the rules, why don't we just relax it a little bit? Our company uses a capitalized name for our repos internally so this is quite annoying given that we cannot automatically link our container image by repo name anymore.

**Comment by sudo-bmitch** [comment]
I don't believe there's any easy way to change this at this point without breaking a lot of code that validates image names. How would a change like this be rolled out without breaking existing runtimes and client tooling?

**Comment by wizpresso-steve-cy-fan** [comment]
> Would this also mean that `registry.example.org/project:tag` would be a different project from `registry.example.org/Project:tag`? If so, that feels like a high risk of typo squatting attacks

That's a good point!
