### ISSUE TITLE
Is there any plan for Reference API to be a stable release

### ISSUE THREAD

**Issue by njucjc** [opencontainers/distribution-spec#468]
Is there any plan for Reference API to be a stable release.

**Comment by sudo-bmitch** [comment]
Yes, we are going through the RC process now. Once finished, there will be a GA release. OCI does not set dates for a release, instead the maintainers will [vote](https://github.com/opencontainers/distribution-spec/blob/main/GOVERNANCE.md#voting) when it's believed to be ready.
