### ISSUE TITLE
Remove references to docker v2 schema 1 manifests

### ISSUE THREAD

**Issue by jonjohnsonjr** [opencontainers/distribution-spec#47]
The examples for pulling and pushing an image use docker v2 schema 1 images, e.g.

https://github.com/opencontainers/distribution-spec/blob/fb183ce74113c89a64b55ef2d877277268f9a8af/spec.md#pulling-an-image

https://github.com/opencontainers/distribution-spec/blob/fb183ce74113c89a64b55ef2d877277268f9a8af/spec.md#pushing-an-image-manifest

https://github.com/opencontainers/distribution-spec/blob/fb183ce74113c89a64b55ef2d877277268f9a8af/spec.md#on-success-ok-3

https://github.com/opencontainers/distribution-spec/blob/fb183ce74113c89a64b55ef2d877277268f9a8af/spec.md#put-manifest

Similarly we have a lot of references to signatures that aren't part of the OCI image format.

**Comment by dmcgowan** [comment]
I agree it would be better to use OCI manifest examples. We don't everyone to just forget schema1 exists.

**Comment by atlaskerr** [comment]
Dibs.

**Comment by vbatts** [comment]
@atlaskerr taking point on this. says it's about closed out

**Comment by vbatts** [comment]
@atlaskerr ?

**Comment by atlaskerr** [comment]
@vbatts This issue can be closed now!

**Comment by jonjohnsonjr** [comment]
There's still a lot of references to signatures in there that we could prune, I think. Ctrl+f "signature" and read the context -- they're not really relevant to OCI. We might link out to schema 1 spec or something, but it's confusing to read about signatures when the image spec doesn't mention them anywhere.

**Comment by atlaskerr** [comment]
@jonjohnsonjr Good catch. I'll open up another PR.

It's a work in progress guys; we'll get there eventually!

**Comment by jonjohnsonjr** [comment]
This isn't quite done, should we open a separate issue for the signature stuff?

**Comment by vbatts** [comment]
Ah, sorry @jonjohnsonjr. I didn't see that there was still an open topic. Please do open an issue for that specifically.

**Comment by jonjohnsonjr** [comment]
Opened https://github.com/opencontainers/distribution-spec/issues/60 for followup.
