### ISSUE TITLE
How to conformance test minimal compliant spec (pull only)

### ISSUE THREAD

**Issue by smndtrl** [opencontainers/distribution-spec#503]
Hi,

is there a way to to verify a system that fulfills the minimal requirements of the spec (All registries conforming to this specification MUST support, at a minimum, all APIs in the Pull category.) with the provided conformance test suite?
Even when running with all other `OCI_TEST_...` set to `0`, setup and teardown still push layers, manifests, tags.

For context, I'm working on a separate read-only frontend part of "compatible" registry.

**Comment by sudo-bmitch** [comment]
Did you use the options steps listed at: https://github.com/opencontainers/distribution-spec/blob/main/conformance%2FREADME.md#pull

**Comment by smndtrl** [comment]
OMG, I didn't scroll down enough. My bad
