### ISSUE TITLE
Question regarding refferres API conformance tests for push

### ISSUE THREAD

**Issue by suleimi** [opencontainers/distribution-spec#518]
Hello!

With the release of v1.1.0 of the spec it seems there isn't the option to skip the conformance tests related to the referrers API alone.  From https://github.com/opencontainers/distribution-spec/blob/main/spec.md#backwards-compatibility it seems the referrers API is optional . 

Is my understanding correct that the referrers API is optional (and clients of registries will be responsible to implement the fallback if the API is not available)? and if this is indeed the case can we expose a flag in the conformance tests to enable older registries (that don't implement the referrers API) to skip referrers API tests specifically and not just all the service-discovery tests?

**Comment by sudo-bmitch** [comment]
The backward compatibility is for clients working with registries that implement the 1.0.x version of the spec. If you do not want to implement the latest APIs, and only want to support OCI 1.0.x, you can run older releases of the conformance tests.
