### ISSUE TITLE
Conformance teardown test deleteManifestBeforeBlobs should allow return 400 when delete by tag is disallowed by registry

### ISSUE THREAD

**Issue by MinerYang** [opencontainers/distribution-spec#524]
when running deleteManifestBeforeBlobs tear down test, contains delete by tag reference, which some of the registry is disallowed delete manifest by tag, according to https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#deleting-tags, it should also include the Equal(http.StatusBadRequest) to satisfy the conditions. 
https://github.com/opencontainers/distribution-spec/blob/0f98d91a0afe7ed3ab0f29349beed2bb4ba1507d/conformance/03_discovery_test.go#L409

**Comment by sudo-bmitch** [comment]
It currently does include a check for bad requests:
https://github.com/opencontainers/distribution-spec/blob/main/conformance%2F03_discovery_test.go#L409

**Comment by sudo-bmitch** [comment]
@MinerYang thanks for the report. I've opened up #525 which I believe resolves this. Let us know if that works for you.
