### ISSUE TITLE
Idea: GoLang specs for V2 new media types like `application/vnd.docker.distribution.manifest.v2+json`

### ISSUE THREAD

**Issue by ffguven** [opencontainers/distribution-spec#532]
Hi, 

I'm looking for GoLang specs for new media types such as ` application/vnd.docker.distribution.manifest.v2+json`, but the existing specs (https://github.com/opencontainers/distribution-spec/tree/v1.0.1/specs-go) does not contain GoLang specs (struct definitions) for these media types.

Is there any plan to add such specs for V2 media types?

I found https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/manifest.go super useful, and having the similar approach in the `distribution-spec` repository for v2 manifests would save lots of people from implementing the same struct again and again.

Thanks!

**Comment by sudo-bmitch** [comment]
I don't believe there's any plan to include 3rd party vendor specs within the OCI specs. That would be out of scope. In Docker, they import from [distribution/distribution](https://github.com/distribution/distribution/tree/main/manifest/schema2) that they have donated to the CNCF.

**Comment by tianon** [comment]
FWIW, the documentation for those media types can be found at https://github.com/distribution/distribution/blob/v3.0.0-alpha.1/docs/content/spec/manifest-v2-2.md

**Comment by tianon** [comment]
(and for further context, they are not "new" despite the version number in them - they predate and were the original reference for what became the v1 OCI media types ❤️)
