### ISSUE TITLE
Ensure flexibility for unspecified media types

### ISSUE THREAD

**Issue by jzelinskie** [opencontainers/distribution-spec#55]
This is a task for auditing the spec to make sure that nothing in the distribution specification prevents unspecified media types from being used for descriptors.

Related: https://github.com/opencontainers/image-spec/pull/759

**Comment by vbatts** [comment]
The corresponding PR is merged. What is needed here?

**Comment by jzelinskie** [comment]
I need to skim over the spec to see if anything is blocking this. I think @jdolitsky and @stevvooe need to take a look as well.

We might want to clarify interactions around registries electing to reject specific content types on `PUT /v2/<name>/manifests/<reference>`. Maybe there should be an explicit error code for it, otherwise we're stuck using invalid manifest: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#put-manifest

**Comment by jzelinskie** [comment]
I think we can close this since the only change that had to be made was in image-spec and now we have the artifact repository.
