### ISSUE TITLE
Referrer API order and sorting

### ISSUE THREAD

**Issue by asafalgawi** [opencontainers/distribution-spec#553]
According to the (original?) referrer API spec found on ORAS: https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#sorting-results

The referrer API must support sorting by age using the created at annotation. 

This is not mentioned in the referrer API spec found on the distribution API page here: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers

So was it removed from the spec or omitted by mistake?

**Comment by sudo-bmitch** [comment]
Sorting was never added to the OCI spec. You can see the development of it in the working group at https://github.com/opencontainers/wg-reference-types

The ORAS project, and the ORAS artifacts are independent and separate from the OCI work. Several of their maintainers are here, and they were included in the working group. Several implementation decisions in OCI were made at their request to look similar to the ORAS implementation. But calling them the original implementation of the OCI spec would not be accurate.

**Comment by asafalgawi** [comment]
Thanks for the clarification :)
