### ISSUE TITLE
Question regarding error codes for distribution spec

### ISSUE THREAD

**Issue by git-hyagi** [opencontainers/distribution-spec#554]
Hi!

In the ["Pushing Manifests"](https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#pushing-manifests) section, it mentions that the registry should respond with a code "_413 Payload Too Large_":

> "A registry SHOULD enforce some limit on the maximum manifest size that it can accept. A registry that enforces this limit SHOULD respond to a request to push a manifest over this limit with a response code 413 Payload Too Large."

However, according to the definition in the ['Error Codes'](https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#error-codes) section, the registry MUST follow one of the errors defined in the table, even though '_413 Payload Too Large_' is not included. This discrepancy seems to cause confusion and allows for different implementations, leading to a lack of standardization and conformance:
https://github.com/opencontainers/distribution-spec/issues/260#issuecomment-893069598

> gcr.io [..] fails with UNKNOWN: Bad Request.
> quay.io [..] fails with 413 Request Entity Too Large (an nginx error, not a spec error)
> docker.io [..] MANIFEST_INVALID: manifest invalid; http: request body too large
> 

Am I looking at the wrong place and _"413 Payload Too Large_" is a valid error?

**Comment by sudo-bmitch** [comment]
#293 specified the status code without updating the endpoints table. That's easy enough to fix with a PR to the endpoints table to add the status code.

**Comment by sudo-bmitch** [comment]
Also, the "Error codes" are part of the JSON body that a registry MAY return. The status codes are part of the HTTP headers included with every valid HTTP response. These two things are not the same.

The HTTP 413 status code is documented in the RFC: https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.11

**Comment by git-hyagi** [comment]
Got it. Thank you for the explanations and the quick fix!
