### ISSUE TITLE
Clear Error Codes for unsupported mediaType

### ISSUE THREAD

**Issue by vbatts** [opencontainers/distribution-spec#58]
(from the weekly discussion)

Regardless of whether a registry implements whitelist or blacklist.
With out divulging information, but giving the client an informed error code when the mediatype being pushed is rejected. 
Like HTTP 415?

**Comment by atlaskerr** [comment]
I think the only endpoints that should return a `415 Unsupported Media Type` is the `PUT` and `GET` operation at the `/v2/<name>/manifests/<reference` endpoint. All the other operations are mediatype agnostic.

**Comment by vbatts** [comment]
oh this may be tricky. when it's pushing the blob isn't the right time.
The registry would have to process the manifest before returning this error code.

**Comment by stevvooe** [comment]
We already have `UNSUPPORTED` for this, no?

**Comment by jzelinskie** [comment]
Oh wow, lol. I think I just posted about this in the other issue.

I'm +1 for reusuing UNSUPPORTED, we just have to copy it into the table for error messages received when doing `/v2/<name>/manifests/<reference>`. I agree with Atlas that we shouldn't do anything during blob uploads.

**Comment by vbatts** [comment]
so, https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-not-allowed already does this, but it's a `405` not a `415`. I think this is fine.

**Comment by vbatts** [comment]
closing for now (unless someone wants to make the language more clear in the doc)

**Comment by mikebrow** [comment]
> so, https://github.com/opencontainers/distribution-spec/blob/master/spec.md#on-failure-not-allowed already does this, but it's a `405` not a `415`. I think this is fine.

"or for some other reason" is a bit vague but seems to cover this case. Let's address doc clean up like adding optional error examples with a different issue and this can be one of many :)
