### ISSUE TITLE
spec: split up sections to separate .md files

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/distribution-spec#62]
The [distribution spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md) currently has greater than 4,500 lines. Attempting to find or edit a section becomes a tedious task.

Issue is to break the spec up into logical units, similar to the [image-spec](https://github.com/opencontainers/image-spec/).

**Comment by vbatts** [comment]
:+1:

**Comment by jzelinskie** [comment]
As long as the split makes sense; I find that the image spec's layout is
suboptimal because it jumps across files and sometimes has cyclic
references.

**Comment by SteveLasker** [comment]
I’ll make a TOC proposal for review, before making a split up PR

**Comment by SteveLasker** [comment]
As I started to consider a new TOC, I wondered what opinions were on links to the current spec, including anchors. 
Before I make a new TOC proposal, would some block is it could break links like: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#initiate-blob-upload

**Comment by jonjohnsonjr** [comment]
> As long as the split makes sense; I find that the image spec's layout is suboptimal because it jumps across files and sometimes has cyclic references.

I tend to agree. GitHub's search is... not great, so splitting across pages makes it nearly impossible to find anything. Right now I can just Ctrl+F within the page.

**Comment by vbatts** [comment]
lets not split up just now. Instead lets look at the reorg #126
