### ISSUE TITLE
Content-Digest: digest algorithm requirement is ambiguous

### ISSUE THREAD

**Issue by simonferquel** [opencontainers/distribution-spec#63]
In https://github.com/opencontainers/distribution-spec/blob/master/spec.md#content-digests, the following statement fill a bit ambiguous to me:
> While the algorithm does allow one to implement a wide variety of algorithms, compliant implementations SHOULD use sha256

The ambiguity is on the _SHOULD_ word: if my registry uses sha512 for digesting contents (and thus for OCI descriptors), is it still compliant to the spec ?

More importantly, as a consumer of the registry API, can I rely on the fact that all OCI-compliant registries use sha256 for their descriptors ?
If it is not the case, it is a very serious limitation for interoperability: it means that I cant update a manifest with its dependencies in OCI Image layout from registry-a and be sure I can upload it as-is in registry-b. If the 2 registries use different digest algorithms for their descriptors, I need to modify all the descriptors in my manifests when doing a copy.
It also means that any digital signature I have for trusting a given manifest from registry-a can't be used to validate the same manifest once copied on registry-b (because my descriptors would have been rewritten).

**Comment by SteveLasker** [comment]
This is a valid point as we start to see more and more images moved across registries, as a best practice. 
We need:
a means for an image/artifact to be signed, at the content level
a means to move the artifact between registries, while maintaining it's integrity 
If we're using the digest, it does need to be consistently supported on all instances of distribution.

The questions that come to mind:
-Do any registries implement something other that sha256?
-To convert to sha512 means re-computing all existing digests. Is this even a realistic ask?

Should sha256 be the standard? 
If there's a need to do sha512, is that a new version of the registry? An optional, additional signature, when requested?

**Comment by simonferquel** [comment]
Maybe having a way when posting a blob/manifest to explicitly specify the digesting algorithm to use for creating locators to the resource would be nice (the spec could specify that at least sha256 must be supported for backward compat with existing registries and that they may support other algorithms as well).

**Comment by dmcgowan** [comment]
> Should sha256 be the standard?
Yes, however I don't think this needs to be stated stronger than "SHOULD".  All registries today implement this, however if clients switch to another algorithm a registry could handle it or the registry chooses to return a different algorithm the client should handle it. From a registry perspective allowing multiple algorithms may cause duplication issues on the backend if they are not prepared for it, so making it a requirement to support any algorithm doesn't seem reasonable. In my opinion everyone should continue using sha256 until there is a compelling reason to move to something proven to be much stronger (not just sha512).

> specify the digesting algorithm to use for creating locators to the resource would be nice
Is this specific to the manifest endpoints? All registries today compute the sha256 and make the manifests also available by that digest, however I am not aware if any registries are computing multiple hashes when a manifest is uploaded by tag name. For any operation with blobs, the algorithm is specified, but are you suggesting that registries could/should compute multiple hashes to index the content in the backend by?

**Comment by vbatts** [comment]
PTAL #75
