### ISSUE TITLE
Requirements: Artifact Signing

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/distribution-spec#70]
# OCI Artifact Signing - Requirements

As containers become the [common unit of deployment](https://stevelasker.blog/2016/05/26/docker-containers-as-the-new-binaries-of-deployment/), users want to know the images in their private registries and their deployments are the same images that were initially published.

The [OCI TOB][oci-tob] has adopted [OCI Artifacts][artifacts-repo], generalizing container images as one of many types of artifacts that may be stored in a registry. Other artifact types currently include:

* [Singularity][singularity]
* [Helm Charts][helm-registry]
* Car firmware updates, deployed from OCI Artifact registries

## The Need for a Generalized Signing Solution

This document serves as the requirements and constraints of a generalized signing solution. It focused on the scenarios and needs, and very specifically avoids any reference to other projects or implementations. As our working group forms a consensus on the requirements, the group will then transition to a spec. Existing verification & signing solutions can be compared against the requirements and spec to identify best fits. 

## Key Stake Holders & Contributors

As we identify the requirements and constraints, a number of key contributors will be asked to represent their requirements and constraints.

> Please add companies, projects, products that you believe should be included.

* Registry Cloud Operators
  * [Azure Container Registry (acr)][acr] - Steve Lasker <steve.lasker@microsoft.com> (@stevelasker)
  * [AWS Container Registry (ecr)][ecr]
  * [Docker Hub][docker-hub]
  * [Google Container Registry (gcr)][gcr]
  * [GitHub Package Registry (gpr)][gpr]
  * [Quay][quay]
  * [IBM Cloud Container Registry (icr)][icr]
* Registry Vendors, Projects & Products
  * [Docker Trusted Registry][docker-dtr]
  * [Harbor][harbor]
  * [JFrog Artifactory][jfrog]
* Artifact Types
  * Container Images - OCI Org
  * Helm Charts
  * Singularity

## Requirements

As we begin a new design, we must ask what defines success.

### Generic Artifact Support

While Docker Content Trust focused on container images, registries have evolved to now support any type of artifact. An image is just one of many artifacts. As a result, OCI has adopted [OCI Artifacts](https://github.com/opencontainers/artifacts) 

As we consider a new signing solution, we look to support any artifact to be signed, including images, Helm charts, OPA bundles, Singularity High Performance Computing images, to new, yet unknown artifacts. 

### Artifact Movement

1. As part of normal workflows, users move artifacts from one **repository** to another**. The movement of the artifact from dev-->staging-->production must not invalidate the signature.
1. As part of normal workflows, users move artifacts from one **registry** to another. The movement of the artifact must not invalidate the signature.
1. Users acquire artifacts from public registries, representing products. As they copy the artifact to their private registry, the signature must be verifiable as that of the source.

### Signature Movement

1. Users place network rules on their deployments. These network rules restrict connections to trusted endpoints within the users control. The signature must be verifiable without having to reach untrusted endpoints. A user must be able to move signature information to services the user runs, and subsequently trusts.

### Registry Operator Differentiated Value

1. Registry operators must be able to leverage other systems within their product and service lines. Specifically, the spec must allow for:

    1. External key management - leveraging other services they may provide
    1. Blob storage - leveraging unique cloud provider storage solutions
    1. Integrated authentication and authorization - while the spec must account for auth flows, each cloud provider must be able to provide flows that incorporate 2FA and service accounts

## Open Topics

The following accounts for the list of open topics that should be considered.

### Parking Log / Backlog

This section accounts for any topics the working group deems deferred for current conversation.

[artifacts-repo]:   https://github.com/opencontainers/artifacts
[helm-registry]:    https://v3.helm.sh/docs/topics/registries/
[oci-tob]:          https://github.com/opencontainers/tob
[singularity]:      https://github.com/sylabs/singularity
[acr]:              https://aka.ms/acr/artifacts
[ecr]:              https://aws.amazon.com/ecr/
[docker-hub]:       https://hub.docker.com/
[docker-dtr]:       https://www.docker.com/products/image-registry
[gcr]:              https://cloud.google.com/container-registry/
[gpr]:              https://github.com/features/package-registry
[quay]:             https://quay.io/
[harbor]:           https://goharbor.io/
[jfrog]:            https://jfrog.com/integration/docker-registry/
[icr]:              https://icr.io/

**Comment by wking** [comment]
An important design constraint is whether additional sigs can be added without changing the root image digest (i.e. what the mutable tag points to).  If bumping tags is ok, sigs can live in CAS.  If tags cannot be bumped, tags must live outside of CAS.

**Comment by wking** [comment]
Previous discussion in opencontainers/image-spec#22, opencontainers/image-spec#176, and opencontainers/image-spec#400.

**Comment by jtoberon** [comment]
> An important design constraint is whether additional sigs can be added without changing the root image digest (i.e. what the mutable tag points to). If bumping tags is ok, sigs can live in CAS. If tags cannot be bumped, tags must live outside of CAS.

@wking Can you add more details to your note? When you say "can live in CAS," do you just mean within the manifest like in schema 1?

**Comment by wking** [comment]
> When you say "can live in CAS," do you just mean within the manifest like in schema 1?

Manifests get [pulled by reference][1], and references [can be names or digest][2], so they're content addressable, but also tag-addressable (presumably to make space for HTTP content-negotiation for compat with clients who don't understand new media types).  But now we have [indexes][3], which are kind of tiptoeing into in-CAS content negotiation.  By "in CAS" I mean "is pushed as an opaque blob and retrieved by digest", like we currently use [for layers][4].  It would be nice to be able to push whatever types you want (including signature objects) into the CAS blob store, and then push an array of [descriptors][5] as the mutable tag.  Clients would request the tag by name, and the server would select an entry based on content negotiation `Accept` headers vs. the media types in the tag's descriptors.  Then signed content looks like a `GET /<repo-name>/tag/<tag-name>` with `Accept: some-signature-type`, possibly with fallbacks in `Accept` to index, manifest, etc. types if you can accept unsigned content (e.g. because you're going to follow-up and verify the resulting digest with Notary or some other non-CAS signature store).

[1]: https://github.com/opencontainers/distribution-spec/blame/v1.0.0-rc0/spec.md#L308
[2]: https://github.com/opencontainers/distribution-spec/blame/v1.0.0-rc0/spec.md#L312
[3]: https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md
[4]: https://github.com/opencontainers/distribution-spec/blame/v1.0.0-rc0/spec.md#L400
[5]: https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md

**Comment by SteveLasker** [comment]
Adding links to Notary v2 efforts, and closing this issue as it's being tracked separatley:
- [Notary v2 Requirements](https://github.com/notaryproject/requirements)
- [Notary v2 Scenarios](https://github.com/notaryproject/requirements/blob/main/scenarios.md)
- [Notary v2, Prototype-1](https://github.com/notaryproject/nv2/blob/prototype-1/README.md)
