### ISSUE TITLE
Put Blob Upload return code should be 201

### ISSUE THREAD

**Issue by amouat** [opencontainers/distribution-spec#86]
The spec defines the return type from a PUT Blob operation to be a 204 https://github.com/opencontainers/distribution-spec/blob/master/spec.md#put-blob-upload, but this disagrees with the conformance test https://github.com/opencontainers/distribution-spec/blob/master/conformance/03_blob_upload_monolithic_test.go#L29-L37.

As the conformance test agrees with existing implementations, and the 204 code seems inconsistent with other areas of the spec (e.g. PUT manifest returns a 201), I suggest the spec should be changed to show a 201 return.

**Comment by jonjohnsonjr** [comment]
Tracked in https://github.com/opencontainers/distribution-spec/issues/68 as well.

**Comment by jdolitsky** [comment]
This seems to be addressed. See current table of endpoints and status codes: https://github.com/opencontainers/distribution-spec/blob/master/spec.md#endpoints
