### ISSUE TITLE
unclear wording in the spec: "recoverable error"

### ISSUE THREAD

**Issue by majewsky** [opencontainers/distribution-spec#92]
On current master, under the heading "Initiate Monolithic Blob Upload", the spec says ([here](https://github.com/opencontainers/distribution-spec/blob/668a6a9230f2c5212e521b97e2a5cf78144b5859/spec.md#initiate-monolithic-blob-upload)):

> This upload will not be resumable unless a recoverable error is returned.

This is the only occurrence of the word "recoverable" in the spec, and it is not clear which types of errors should be considered recoverable.

In my own implementation of blob upload, I'm treating all errors during monolithic blob upload as non-recoverable: Either the blob gets uploaded and 201 is returned, or it's not uploaded and 4xx/5xx is returned (i.e. the client would have to resend the request entirely). There's no inbetween. This particular part of the spec should clarify which errors are considered recoverable, and what recoverability even means for a single-request workflow.

For context: On the PATCH endpoint that's used for streamed and chunked upload, the wording is clearer since for 400 and 404 responses, it says that the upload "MUST be restarted". So it appears that 400 and 404 would be non-recoverable, whereas 401, 403 and 429 are recoverable.

**Comment by jdolitsky** [comment]
The word "recoverable" is no longer in the spec. Closing for now.
