### ISSUE TITLE
Minor error in pagination section

### ISSUE THREAD

**Issue by amouat** [opencontainers/distribution-spec#94]
Under https://github.com/opencontainers/distribution-spec/blob/master/spec.md#pagination

The text reads "If the value of n is 2, v1 and v1 will be returned", presumably this should be "If the value of n is 2, v1 and *v2* will be returned".

**Comment by vbatts** [comment]
hah, yes.
Would you mind opening a PR for this?

**Comment by amouat** [comment]
Sure. I probably should have just done that in the first place...
